name: Update PR Description

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  update_pr_description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate PR Description
        run: |
          echo "## Automated PR Description" > pr_body.md
          echo "### Commits in this PR:" >> pr_body.md
          git log --format="- %s%n%n  %b" origin/${{ github.base_ref }}..origin/${{ github.head_ref }} >> pr_body.md


      - name: Read PR Body
        id: pr_body
        run: |
          body=$(cat pr_body.md)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=content::$body"

      - name: Update PR
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch-regex: '.*'
          head-branch-regex: '.*'
          body-template: |
            ${{ steps.pr_body.outputs.content }}
          body-update-action: "suffix"
          body-newline-count: 2
